app:
  name: CurrenceExchangeApp
  port: :3000

database:
  dns: "root:123456@tcp(192.168.189.129:3308)/exchangeAPP?charset=utf8mb4&parseTime=True&loc=Local"
  MaxIdleConns: 10
  MaxOpenCons: 100

redis:
  ip: "192.168.189.129"
  port: ":6380"
